# Generated by Django 4.1.1 on 2022-10-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
